require [
  'jquery'
  'handlebars'
  'lib/view-helper'
  'templates'
  'test/templates'
  'bootstrap_button'
  'bootstrap_collapse'
  'bootstrap_dropdown'
  'bootstrap_modal'
  'bootstrap_tab'
  'bootstrap_tooltip'
  'bootstrap_transition'
  'stickit'
]
